<a href="https://colab.research.google.com/github/Ian-Ibrahim/SU-Machine-learning-1222785/blob/main/B_122785_Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Set Up Env.
grid_rows = 2
grid_cols = 3
num_actions = 4

# Define the reward matrix
rewards = np.array([
    [-10, 1, 0],
    [0, -10, 10]
])
print(rewards)

[[-10   1   0]
 [  0 -10  10]]


In [ ]:

# Define the Q-Table
q_table = np.zeros((grid_rows,grid_cols,num_actions)) # Fill in the blank



In [ ]:
# Set hyper-parameters
alpha = 0.1  # learning rate
gamma = 0.9  # discount factor
epsilon = 0.1  # exploration rate
learningRate=0.1

In [ ]:
print(q_table)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
actions = ['up', 'right', 'down', 'left']

In [ ]:
def is_terminal_state(row_index, col_index):
    if row_index == 1 and col_index ==2:
        return True
    else:
        return False

In [ ]:
terminal=is_terminal_state(1,0)
print(terminal)

False


In [ ]:
# randomly pick a location
def get_start_loc():
  cur_row_index=np.random.randint(grid_rows)
  cur_col_index=np.random.randint(grid_cols)
  while is_terminal_state(cur_row_index,cur_col_index):
    cur_row_index=np.random.randint(grid_rows)
    cur_col_index=np.random.randint(grid_cols)
  return cur_row_index,cur_col_index

In [ ]:
def get_next_loc(cur_row_index,cur_col_index,action_index):
  new_row_index=cur_row_index
  new_col_index=cur_col_index

  if actions[action_index]=='up' and cur_row_index>0:
    new_row_index-=1
  elif actions[action_index]=='down' and cur_row_index<grid_rows-1:
    new_row_index+=1
  elif actions[action_index]=='right' and cur_col_index<grid_cols-1:
    new_col_index+=1
  elif actions[action_index]=='left' and cur_col_index>0:
    new_col_index-=1

  return new_row_index,new_col_index

In [ ]:

def get_next_act(cur_row_index, cur_col_index, epsilon):
    if np.random.random() < epsilon:
        return np.random.randint(num_actions)
    else:
        return np.argmax(q_table[cur_row_index, cur_col_index])


In [ ]:
def get_shortest_path(start_row, start_col):
  if is_terminal_state(start_row, start_col):
    return []
  else:
    cur_row_index,cur_col_index=start_row, start_col
    shortest_path =[]
    shortest_path.append([cur_row_index,cur_col_index])
    while not is_terminal_state(cur_row_index, cur_col_index):
      print("Current position:", cur_row_index, cur_col_index)
      action_index = get_next_act(cur_row_index, cur_col_index, 1.)
      cur_row_index, cur_col_index = get_next_loc(cur_row_index, cur_col_index, action_index)
      shortest_path.append([cur_row_index, cur_col_index])


    return shortest_path

In [ ]:
print(q_table)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
for episode in range(20000):
    row_index, col_index = get_start_loc()

    while not is_terminal_state(row_index, col_index):
        action_index = get_next_act(row_index, col_index, epsilon)

        old_row_index, old_col_index = row_index, col_index
        row_index, col_index = get_next_loc(row_index, col_index, action_index)

        reward = rewards[row_index,col_index]
        old_q_value=q_table[row_index,col_index,action_index]
        td = reward+  (gamma * np.max(q_table[row_index, col_index])) - old_q_value
        new_q_value=old_q_value+(learningRate*td)
        q_table[old_row_index, old_col_index ,action_index]=new_q_value
print('training complete')

training complete


In [ ]:
print(q_table)

[[[-8.371       1.81        0.71999259 -8.371     ]
  [10.          0.9        -1.         -8.371     ]
  [ 0.9         0.9         1.         -6.5339    ]]

 [[-8.371       0.8         0.71999259  0.71999983]
  [10.          1.         -1.          0.71999985]
  [ 0.          0.          0.          0.        ]]]


In [ ]:
moves_limit=4

In [ ]:
for episode in range(20000):
    row_index, col_index = get_start_loc()
    moves=0
    while not is_terminal_state(row_index, col_index):
        action_index = get_next_act(row_index, col_index, epsilon)

        old_row_index, old_col_index = row_index, col_index
        row_index, col_index = get_next_loc(row_index, col_index, action_index)

        reward = rewards[row_index,col_index]
        old_q_value=q_table[row_index,col_index,action_index]
        td = reward+  (gamma * np.max(q_table[row_index, col_index])) - old_q_value
        new_q_value=old_q_value+(learningRate*td)
        q_table[old_row_index, old_col_index ,action_index]=new_q_value
        if row_index == 1 and col_index == 2:
          moves=0
        else:
          moves+=1
        if moves>=moves_limit:
          break
print('training complete')

training complete


In [ ]:
print(q_table)

[[[-8.371   1.81    0.72   -8.371 ]
  [10.      0.9    -1.     -8.371 ]
  [ 0.9     0.9     1.     -6.5339]]

 [[-8.371   0.8     0.72    0.72  ]
  [10.      1.     -1.      0.72  ]
  [ 0.      0.      0.      0.    ]]]


In [ ]:
print(get_shortest_path(0,0))

False
Current position: 0 0
3
Current position: 0 0
2
Current position: 1 0
3
Current position: 1 0
0
Current position: 0 0
3
Current position: 0 0
1
Current position: 0 1
1
Current position: 0 2
3
Current position: 0 1
2
Current position: 1 1
3
Current position: 1 0
3
Current position: 1 0
0
Current position: 0 0
0
Current position: 0 0
2
Current position: 1 0
2
Current position: 1 0
1
Current position: 1 1
3
Current position: 1 0
2
Current position: 1 0
2
Current position: 1 0
3
Current position: 1 0
3
Current position: 1 0
1
Current position: 1 1
3
Current position: 1 0
0
Current position: 0 0
0
Current position: 0 0
1
Current position: 0 1
1
Current position: 0 2
2
[[0, 0], [0, 0], [1, 0], [1, 0], [0, 0], [0, 0], [0, 1], [0, 2], [0, 1], [1, 1], [1, 0], [1, 0], [0, 0], [0, 0], [1, 0], [1, 0], [1, 1], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 1], [1, 0], [0, 0], [0, 0], [0, 1], [0, 2], [1, 2]]


NameError: ignored